### ISSUE TITLE
pliss help me

### ISSUE THREAD

**Issue by DeskiAriSandi** [kitabisa/teler-waf#156]
How do I configure it so that Teler can work with fail2ban?
because I am doing this configuration for a case study in my thesis
I have tried to configure according to https://dwisiswant0.medium.com/empowering-teler-http-intrusion-detection-as-waf-with-fail2ban-35c40618890 but when looking at fail2ban-client the status does not change to teler

**Comment by dwisiswant0** [comment]
First off, you have to understand what the issue section is all about. Don't go spamming outside the repo context.

Secondly, if you're gonna reference my article, I wrote it as is — now it's prolly **outdated**, hence [teler-waf](https://github.com/kitabisa/teler-waf) & [teler-proxy](https://github.com/kitabisa/teler-proxy) were created. You have to figure out for yourself if there's a glitch or a diff in expectations.

Thanks.
