### ISSUE TITLE
[bug] can't running echo server

### ISSUE THREAD

**Issue by sautmanurung1** [kitabisa/teler-waf#36]
**Describe the bug**

I can't running code because i got some error, it likes screenshoot

**To Reproduce**

- first i install the library 
- second i install the echo framework 
- third i copy the code it likes code in folder example/integration/echo
- fourth if i running the code i got the error it likes screenshoot 

```go
go run main.go
```

**Expected behavior**

**Screenshots**

![Screenshot 2023-04-20 222500](https://user-images.githubusercontent.com/68042498/233414405-ed4ccd75-dea7-4094-aaa2-55d5ed9530d2.png)

**Environment (please complete the following information):**

- OS: [windows]
- OS version: [11]
- teler Version [v0.5.0]

**Additional context**

Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by dwisiswant0** [comment]
Hey @sautmanurung1, to compile teler-waf on Windows, you need to install [the dependencies](https://github.com/kitabisa/teler-waf#install).
