### ISSUE TITLE
[bug] improper client IP is captured in getClientIP util func

### ISSUE THREAD

**Issue by dwisiswant0** [kitabisa/teler-waf#58]
**Describe the bug**

**To Reproduce**

```go
Your teler usage & options...
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. mac, linux]
- OS version: [uname -a]
- teler Version [see go.mod]

**Additional context**

Add any other context about the problem here. Full output log is probably a helpful thing to add here.

**Comment by DeskiAriSandi** [comment]
saya memiliki masalah yang sama.mohon bantuannya
