### ISSUE TITLE
[feature] more log output option

### ISSUE THREAD

**Issue by fnoopv** [kitabisa/teler-waf#91]
**Is your feature request related to a problem? Please describe.**
I want to view the logs in the browser, so I need to write the logs to the mysql database, but the logs in teler-waf can only be output to files. Can you provide more output methods ?

**Describe the solution you'd like**
provide more output methods

**Describe alternatives you've considered**
[teler.Options](https://pkg.go.dev/github.com/kitabisa/teler-waf#Options) Provider custom log output field, like `LogOutput`, It needs to implement the io.Writer interface

**Additional context**
no

**Comment by dwisiswant0** [comment]
Are you aware that there's an [`FalcoSidekickURL`](https://pkg.go.dev/github.com/kitabisa/teler-waf#Options.FalcoSidekickURL) option available? [Falco Sidekick](https://github.com/falcosecurity/falcosidekick) provides support for various output channels to facilitate the forwarding of teler WAF alerts. See [here](https://github.com/kitabisa/teler-waf#falco-sidekick).

**Comment by fnoopv** [comment]
I know this option, but it is not the optimal solution for log output. This requires listening to a new port to process logs. If you provide a log output option and let the user decide how to output, such as outputting to a database, file, syslog, or others (kafka, etc.), this will have a better user experience. Of course, this is just an optional suggestion, teler-waf is already very good

**Comment by dwisiswant0** [comment]
Our decision to utilize Falco Sidekick as an events forwarder, in addition to considering maintenance considerations[^1], is grounded in our commitment to prioritizing the in-depth analysis of the `http.Request` itself, thus enhancing overall performance.

Nevertheless, we are open to exploring the alternative solutions you have suggested for log output. Please [submit a proposal](https://github.com/kitabisa/teler-waf/issues/new?assignees=dwisiswant0&labels=proposal&projects=&template=proposal.md&title=%5Bproposal%5D+) for consideration.

[^1]: https://github.com/kitabisa/teler/issues/116

**Comment by fnoopv** [comment]
I will try to use it
